'use strict'

export const CHELONIA_RESET = 'chelonia-reset'
export const CONTRACT_IS_SYNCING = 'contract-is-syncing'
export const CONTRACTS_MODIFIED = 'contracts-modified'
export const CONTRACTS_MODIFIED_READY = 'contracts-modified-ready'
export const EVENT_HANDLED = 'event-handled'
export const EVENT_PUBLISHED = 'event-published'
export const EVENT_PUBLISHING_ERROR = 'event-publishing-error'
export const EVENT_HANDLED_READY = 'event-handled-ready'
export const CONTRACT_REGISTERED = 'contract-registered'
export const CONTRACT_UNREGISTERED = 'contract-unregistered'
export const CONTRACT_IS_PENDING_KEY_REQUESTS = 'contract-is-pending-key-requests'
export const CONTRACT_HAS_RECEIVED_KEYS = 'contract-has-received-keys'
export const PERSISTENT_ACTION_FAILURE = 'persistent-action-failure'
export const PERSISTENT_ACTION_SUCCESS = 'persistent-action-success'
export const PERSISTENT_ACTION_TOTAL_FAILURE = 'persistent-action-total_failure'
