export default {
  'blue': {
    'name': 'blue',
    'theme': 'light',
    'primary': '#5dc8f0',
    'primarySaturated': '#5dc8f0',
    'primaryText': '#17b0ea',
    'primaryTextHover': '#fff',
    'secondary': '#a0d10e',
    'tertiary': '#f89201',
    'danger': '#FC6F6F',
    'placeholder': '#dbdbdb',
    'border': '#5DC8F0',
    'bg': '#fff',
    'action': '#FE6E61'
  },
  'green': {
    'name': 'green',
    'theme': 'light',
    'primary': '#c2d879',
    'primarySaturated': '#90BD0D',
    'primaryText': '#ffffff',
    'primaryTextHover': '#363636',
    'secondary': '#a0d10e',
    'tertiary': '#f89201',
    'danger': '#FC6F6F',
    'placeholder': '#dbdbdb',
    'border': '#90BD0D',
    'bg': '#fff',
    'action': '#FE6E61'
  },
  'orange': {
    'name': 'orange',
    'theme': 'light',
    'primary': '#f8b85d',
    'primarySaturated': '#F89302',
    'primaryText': '#17b0ea',
    'primaryTextHover': '#fff',
    'secondary': '#a0d10e',
    'tertiary': '#f89201',
    'danger': '#FC6F6F',
    'placeholder': '#dbdbdb',
    'border': '#F89302',
    'bg': '#fff',
    'action': '#FE6E61'
  },
  'silver': {
    'name': 'silver',
    'theme': 'light',
    'primary': '#adadad',
    'primarySaturated': '#F89302',
    'primaryText': '#17b0ea',
    'primaryTextHover': '#fff',
    'secondary': '#a0d10e',
    'tertiary': '#f89201',
    'danger': '#FC6F6F',
    'placeholder': '#dbdbdb',
    'border': '#999999',
    'bg': '#fff',
    'action': '#FE6E61'
  },
  'black & white': {
    'name': 'black & white',
    'theme': 'dark',
    'primary': '#5dc8f0',
    'primaryBG': '#363636',
    'primaryBGA': 'rgba(244, 243, 244, 0.1)',
    'primarySaturated': '#5dc8f0',
    'primaryText': '#ffffff',
    'primaryTextHover': '#363636',
    'secondary': '#a0d10e',
    'tertiary': '#f89201',
    'danger': '#FC6F6F',
    'placeholder': '#fff',
    'border': 'black',
    'bg': 'rgba(78, 78, 78, 0.7)',
    'action': '#FE6E61'
  }
}
