blank_issues_enabled: false
contact_links:
  - name: Discuss Group Income
    url: https://github.com/okTurtles/group-income/discussions
    about: Use issues to report bugs or request features. Everything else goes here.
    