// flow-typed signature: 5f7850e63495ef9cd2b6a22e16f222b4
// flow-typed version: <<STUB>>/blakejs_v1.1.0/flow_v0.123.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'blakejs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'blakejs' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'blakejs/blake2b' {
  declare module.exports: any;
}

declare module 'blakejs/blake2s' {
  declare module.exports: any;
}

declare module 'blakejs/test_blake2b' {
  declare module.exports: any;
}

declare module 'blakejs/test_blake2s' {
  declare module.exports: any;
}

declare module 'blakejs/util' {
  declare module.exports: any;
}

// Filename aliases
declare module 'blakejs/blake2b.js' {
  declare module.exports: $Exports<'blakejs/blake2b'>;
}
declare module 'blakejs/blake2s.js' {
  declare module.exports: $Exports<'blakejs/blake2s'>;
}
declare module 'blakejs/index' {
  declare module.exports: $Exports<'blakejs'>;
}
declare module 'blakejs/index.js' {
  declare module.exports: $Exports<'blakejs'>;
}
declare module 'blakejs/test_blake2b.js' {
  declare module.exports: $Exports<'blakejs/test_blake2b'>;
}
declare module 'blakejs/test_blake2s.js' {
  declare module.exports: $Exports<'blakejs/test_blake2s'>;
}
declare module 'blakejs/util.js' {
  declare module.exports: $Exports<'blakejs/util'>;
}
