// flow-typed signature: 14bf5d26dd6c59b4b155827a30804a51
// flow-typed version: <<STUB>>/buffer_v5.4.3/flow_v0.123.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'buffer'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'buffer' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'buffer/index' {
  declare module.exports: $Exports<'buffer'>;
}
declare module 'buffer/index.js' {
  declare module.exports: $Exports<'buffer'>;
}
