// flow-typed signature: f8f5695fbf8a3c0f3cba6102c0a58542
// flow-typed version: <<STUB>>/cypress-file-upload_v3.5.0/flow_v0.123.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'cypress-file-upload'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'cypress-file-upload' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'cypress-file-upload/dist/bundle' {
  declare module.exports: any;
}

// Filename aliases
declare module 'cypress-file-upload/dist/bundle.js' {
  declare module.exports: $Exports<'cypress-file-upload/dist/bundle'>;
}
