// flow-typed signature: ff0a6c16a5ffe11dcdf51970bf1cae7b
// flow-typed version: <<STUB>>/eslint-plugin-vue_v6.2.2/flow_v0.123.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-plugin-vue'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-plugin-vue' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-plugin-vue/lib/configs/base' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/configs/essential' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/configs/no-layout-rules' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/configs/recommended' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/configs/strongly-recommended' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/processor' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/array-bracket-spacing' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/arrow-spacing' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/attribute-hyphenation' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/attributes-order' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/block-spacing' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/brace-style' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/camelcase' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/comma-dangle' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/comment-directive' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/component-definition-name-casing' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/component-name-in-template-casing' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/component-tags-order' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/dot-location' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/eqeqeq' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/html-closing-bracket-newline' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/html-closing-bracket-spacing' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/html-end-tags' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/html-indent' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/html-quotes' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/html-self-closing' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/jsx-uses-vars' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/key-spacing' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/keyword-spacing' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/match-component-file-name' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/max-attributes-per-line' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/max-len' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/multiline-html-element-content-newline' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/mustache-interpolation-spacing' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/name-property-casing' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/no-async-in-computed-properties' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/no-boolean-default' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/no-confusing-v-for-v-if' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/no-deprecated-scope-attribute' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/no-deprecated-slot-attribute' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/no-deprecated-slot-scope-attribute' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/no-dupe-keys' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/no-duplicate-attributes' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/no-empty-pattern' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/no-irregular-whitespace' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/no-multi-spaces' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/no-parsing-error' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/no-reserved-component-names' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/no-reserved-keys' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/no-restricted-syntax' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/no-shared-component-data' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/no-side-effects-in-computed-properties' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/no-spaces-around-equal-signs-in-attribute' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/no-static-inline-styles' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/no-template-key' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/no-template-shadow' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/no-textarea-mustache' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/no-unsupported-features' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/no-unused-components' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/no-unused-vars' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/no-use-v-if-with-v-for' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/no-v-html' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/object-curly-spacing' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/order-in-components' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/padding-line-between-blocks' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/prop-name-casing' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/require-component-is' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/require-default-prop' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/require-direct-export' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/require-name-property' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/require-prop-type-constructor' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/require-prop-types' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/require-render-return' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/require-v-for-key' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/require-valid-default-prop' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/return-in-computed-property' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/script-indent' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/singleline-html-element-content-newline' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/sort-keys' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/space-infix-ops' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/space-unary-ops' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/static-class-names-order' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/syntaxes/dynamic-directive-arguments' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/syntaxes/scope-attribute' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/syntaxes/slot-attribute' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/syntaxes/slot-scope-attribute' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/syntaxes/v-bind-prop-modifier-shorthand' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/syntaxes/v-slot' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/this-in-template' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/use-v-on-exact' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/v-bind-style' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/v-on-function-call' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/v-on-style' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/v-slot-style' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/valid-template-root' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/valid-v-bind-sync' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/valid-v-bind' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/valid-v-cloak' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/valid-v-else-if' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/valid-v-else' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/valid-v-for' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/valid-v-html' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/valid-v-if' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/valid-v-model' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/valid-v-on' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/valid-v-once' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/valid-v-pre' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/valid-v-show' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/valid-v-slot' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/valid-v-text' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/utils/casing' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/utils/indent-common' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/utils' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/utils/regexp' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-plugin-vue/lib/configs/base.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/configs/base'>;
}
declare module 'eslint-plugin-vue/lib/configs/essential.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/configs/essential'>;
}
declare module 'eslint-plugin-vue/lib/configs/no-layout-rules.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/configs/no-layout-rules'>;
}
declare module 'eslint-plugin-vue/lib/configs/recommended.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/configs/recommended'>;
}
declare module 'eslint-plugin-vue/lib/configs/strongly-recommended.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/configs/strongly-recommended'>;
}
declare module 'eslint-plugin-vue/lib/index' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib'>;
}
declare module 'eslint-plugin-vue/lib/index.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib'>;
}
declare module 'eslint-plugin-vue/lib/processor.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/processor'>;
}
declare module 'eslint-plugin-vue/lib/rules/array-bracket-spacing.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/array-bracket-spacing'>;
}
declare module 'eslint-plugin-vue/lib/rules/arrow-spacing.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/arrow-spacing'>;
}
declare module 'eslint-plugin-vue/lib/rules/attribute-hyphenation.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/attribute-hyphenation'>;
}
declare module 'eslint-plugin-vue/lib/rules/attributes-order.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/attributes-order'>;
}
declare module 'eslint-plugin-vue/lib/rules/block-spacing.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/block-spacing'>;
}
declare module 'eslint-plugin-vue/lib/rules/brace-style.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/brace-style'>;
}
declare module 'eslint-plugin-vue/lib/rules/camelcase.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/camelcase'>;
}
declare module 'eslint-plugin-vue/lib/rules/comma-dangle.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/comma-dangle'>;
}
declare module 'eslint-plugin-vue/lib/rules/comment-directive.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/comment-directive'>;
}
declare module 'eslint-plugin-vue/lib/rules/component-definition-name-casing.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/component-definition-name-casing'>;
}
declare module 'eslint-plugin-vue/lib/rules/component-name-in-template-casing.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/component-name-in-template-casing'>;
}
declare module 'eslint-plugin-vue/lib/rules/component-tags-order.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/component-tags-order'>;
}
declare module 'eslint-plugin-vue/lib/rules/dot-location.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/dot-location'>;
}
declare module 'eslint-plugin-vue/lib/rules/eqeqeq.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/eqeqeq'>;
}
declare module 'eslint-plugin-vue/lib/rules/html-closing-bracket-newline.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/html-closing-bracket-newline'>;
}
declare module 'eslint-plugin-vue/lib/rules/html-closing-bracket-spacing.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/html-closing-bracket-spacing'>;
}
declare module 'eslint-plugin-vue/lib/rules/html-end-tags.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/html-end-tags'>;
}
declare module 'eslint-plugin-vue/lib/rules/html-indent.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/html-indent'>;
}
declare module 'eslint-plugin-vue/lib/rules/html-quotes.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/html-quotes'>;
}
declare module 'eslint-plugin-vue/lib/rules/html-self-closing.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/html-self-closing'>;
}
declare module 'eslint-plugin-vue/lib/rules/jsx-uses-vars.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/jsx-uses-vars'>;
}
declare module 'eslint-plugin-vue/lib/rules/key-spacing.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/key-spacing'>;
}
declare module 'eslint-plugin-vue/lib/rules/keyword-spacing.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/keyword-spacing'>;
}
declare module 'eslint-plugin-vue/lib/rules/match-component-file-name.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/match-component-file-name'>;
}
declare module 'eslint-plugin-vue/lib/rules/max-attributes-per-line.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/max-attributes-per-line'>;
}
declare module 'eslint-plugin-vue/lib/rules/max-len.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/max-len'>;
}
declare module 'eslint-plugin-vue/lib/rules/multiline-html-element-content-newline.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/multiline-html-element-content-newline'>;
}
declare module 'eslint-plugin-vue/lib/rules/mustache-interpolation-spacing.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/mustache-interpolation-spacing'>;
}
declare module 'eslint-plugin-vue/lib/rules/name-property-casing.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/name-property-casing'>;
}
declare module 'eslint-plugin-vue/lib/rules/no-async-in-computed-properties.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/no-async-in-computed-properties'>;
}
declare module 'eslint-plugin-vue/lib/rules/no-boolean-default.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/no-boolean-default'>;
}
declare module 'eslint-plugin-vue/lib/rules/no-confusing-v-for-v-if.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/no-confusing-v-for-v-if'>;
}
declare module 'eslint-plugin-vue/lib/rules/no-deprecated-scope-attribute.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/no-deprecated-scope-attribute'>;
}
declare module 'eslint-plugin-vue/lib/rules/no-deprecated-slot-attribute.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/no-deprecated-slot-attribute'>;
}
declare module 'eslint-plugin-vue/lib/rules/no-deprecated-slot-scope-attribute.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/no-deprecated-slot-scope-attribute'>;
}
declare module 'eslint-plugin-vue/lib/rules/no-dupe-keys.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/no-dupe-keys'>;
}
declare module 'eslint-plugin-vue/lib/rules/no-duplicate-attributes.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/no-duplicate-attributes'>;
}
declare module 'eslint-plugin-vue/lib/rules/no-empty-pattern.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/no-empty-pattern'>;
}
declare module 'eslint-plugin-vue/lib/rules/no-irregular-whitespace.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/no-irregular-whitespace'>;
}
declare module 'eslint-plugin-vue/lib/rules/no-multi-spaces.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/no-multi-spaces'>;
}
declare module 'eslint-plugin-vue/lib/rules/no-parsing-error.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/no-parsing-error'>;
}
declare module 'eslint-plugin-vue/lib/rules/no-reserved-component-names.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/no-reserved-component-names'>;
}
declare module 'eslint-plugin-vue/lib/rules/no-reserved-keys.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/no-reserved-keys'>;
}
declare module 'eslint-plugin-vue/lib/rules/no-restricted-syntax.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/no-restricted-syntax'>;
}
declare module 'eslint-plugin-vue/lib/rules/no-shared-component-data.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/no-shared-component-data'>;
}
declare module 'eslint-plugin-vue/lib/rules/no-side-effects-in-computed-properties.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/no-side-effects-in-computed-properties'>;
}
declare module 'eslint-plugin-vue/lib/rules/no-spaces-around-equal-signs-in-attribute.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/no-spaces-around-equal-signs-in-attribute'>;
}
declare module 'eslint-plugin-vue/lib/rules/no-static-inline-styles.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/no-static-inline-styles'>;
}
declare module 'eslint-plugin-vue/lib/rules/no-template-key.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/no-template-key'>;
}
declare module 'eslint-plugin-vue/lib/rules/no-template-shadow.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/no-template-shadow'>;
}
declare module 'eslint-plugin-vue/lib/rules/no-textarea-mustache.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/no-textarea-mustache'>;
}
declare module 'eslint-plugin-vue/lib/rules/no-unsupported-features.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/no-unsupported-features'>;
}
declare module 'eslint-plugin-vue/lib/rules/no-unused-components.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/no-unused-components'>;
}
declare module 'eslint-plugin-vue/lib/rules/no-unused-vars.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/no-unused-vars'>;
}
declare module 'eslint-plugin-vue/lib/rules/no-use-v-if-with-v-for.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/no-use-v-if-with-v-for'>;
}
declare module 'eslint-plugin-vue/lib/rules/no-v-html.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/no-v-html'>;
}
declare module 'eslint-plugin-vue/lib/rules/object-curly-spacing.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/object-curly-spacing'>;
}
declare module 'eslint-plugin-vue/lib/rules/order-in-components.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/order-in-components'>;
}
declare module 'eslint-plugin-vue/lib/rules/padding-line-between-blocks.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/padding-line-between-blocks'>;
}
declare module 'eslint-plugin-vue/lib/rules/prop-name-casing.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/prop-name-casing'>;
}
declare module 'eslint-plugin-vue/lib/rules/require-component-is.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/require-component-is'>;
}
declare module 'eslint-plugin-vue/lib/rules/require-default-prop.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/require-default-prop'>;
}
declare module 'eslint-plugin-vue/lib/rules/require-direct-export.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/require-direct-export'>;
}
declare module 'eslint-plugin-vue/lib/rules/require-name-property.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/require-name-property'>;
}
declare module 'eslint-plugin-vue/lib/rules/require-prop-type-constructor.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/require-prop-type-constructor'>;
}
declare module 'eslint-plugin-vue/lib/rules/require-prop-types.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/require-prop-types'>;
}
declare module 'eslint-plugin-vue/lib/rules/require-render-return.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/require-render-return'>;
}
declare module 'eslint-plugin-vue/lib/rules/require-v-for-key.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/require-v-for-key'>;
}
declare module 'eslint-plugin-vue/lib/rules/require-valid-default-prop.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/require-valid-default-prop'>;
}
declare module 'eslint-plugin-vue/lib/rules/return-in-computed-property.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/return-in-computed-property'>;
}
declare module 'eslint-plugin-vue/lib/rules/script-indent.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/script-indent'>;
}
declare module 'eslint-plugin-vue/lib/rules/singleline-html-element-content-newline.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/singleline-html-element-content-newline'>;
}
declare module 'eslint-plugin-vue/lib/rules/sort-keys.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/sort-keys'>;
}
declare module 'eslint-plugin-vue/lib/rules/space-infix-ops.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/space-infix-ops'>;
}
declare module 'eslint-plugin-vue/lib/rules/space-unary-ops.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/space-unary-ops'>;
}
declare module 'eslint-plugin-vue/lib/rules/static-class-names-order.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/static-class-names-order'>;
}
declare module 'eslint-plugin-vue/lib/rules/syntaxes/dynamic-directive-arguments.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/syntaxes/dynamic-directive-arguments'>;
}
declare module 'eslint-plugin-vue/lib/rules/syntaxes/scope-attribute.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/syntaxes/scope-attribute'>;
}
declare module 'eslint-plugin-vue/lib/rules/syntaxes/slot-attribute.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/syntaxes/slot-attribute'>;
}
declare module 'eslint-plugin-vue/lib/rules/syntaxes/slot-scope-attribute.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/syntaxes/slot-scope-attribute'>;
}
declare module 'eslint-plugin-vue/lib/rules/syntaxes/v-bind-prop-modifier-shorthand.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/syntaxes/v-bind-prop-modifier-shorthand'>;
}
declare module 'eslint-plugin-vue/lib/rules/syntaxes/v-slot.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/syntaxes/v-slot'>;
}
declare module 'eslint-plugin-vue/lib/rules/this-in-template.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/this-in-template'>;
}
declare module 'eslint-plugin-vue/lib/rules/use-v-on-exact.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/use-v-on-exact'>;
}
declare module 'eslint-plugin-vue/lib/rules/v-bind-style.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/v-bind-style'>;
}
declare module 'eslint-plugin-vue/lib/rules/v-on-function-call.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/v-on-function-call'>;
}
declare module 'eslint-plugin-vue/lib/rules/v-on-style.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/v-on-style'>;
}
declare module 'eslint-plugin-vue/lib/rules/v-slot-style.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/v-slot-style'>;
}
declare module 'eslint-plugin-vue/lib/rules/valid-template-root.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/valid-template-root'>;
}
declare module 'eslint-plugin-vue/lib/rules/valid-v-bind-sync.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/valid-v-bind-sync'>;
}
declare module 'eslint-plugin-vue/lib/rules/valid-v-bind.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/valid-v-bind'>;
}
declare module 'eslint-plugin-vue/lib/rules/valid-v-cloak.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/valid-v-cloak'>;
}
declare module 'eslint-plugin-vue/lib/rules/valid-v-else-if.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/valid-v-else-if'>;
}
declare module 'eslint-plugin-vue/lib/rules/valid-v-else.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/valid-v-else'>;
}
declare module 'eslint-plugin-vue/lib/rules/valid-v-for.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/valid-v-for'>;
}
declare module 'eslint-plugin-vue/lib/rules/valid-v-html.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/valid-v-html'>;
}
declare module 'eslint-plugin-vue/lib/rules/valid-v-if.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/valid-v-if'>;
}
declare module 'eslint-plugin-vue/lib/rules/valid-v-model.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/valid-v-model'>;
}
declare module 'eslint-plugin-vue/lib/rules/valid-v-on.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/valid-v-on'>;
}
declare module 'eslint-plugin-vue/lib/rules/valid-v-once.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/valid-v-once'>;
}
declare module 'eslint-plugin-vue/lib/rules/valid-v-pre.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/valid-v-pre'>;
}
declare module 'eslint-plugin-vue/lib/rules/valid-v-show.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/valid-v-show'>;
}
declare module 'eslint-plugin-vue/lib/rules/valid-v-slot.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/valid-v-slot'>;
}
declare module 'eslint-plugin-vue/lib/rules/valid-v-text.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/valid-v-text'>;
}
declare module 'eslint-plugin-vue/lib/utils/casing.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/utils/casing'>;
}
declare module 'eslint-plugin-vue/lib/utils/indent-common.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/utils/indent-common'>;
}
declare module 'eslint-plugin-vue/lib/utils/index' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/utils'>;
}
declare module 'eslint-plugin-vue/lib/utils/index.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/utils'>;
}
declare module 'eslint-plugin-vue/lib/utils/regexp.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/utils/regexp'>;
}
