// flow-typed signature: 7edec368c654d2c0849188f0a30a3957
// flow-typed version: <<STUB>>/grunt-contrib-clean_v2.0.0/flow_v0.123.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'grunt-contrib-clean'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'grunt-contrib-clean' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'grunt-contrib-clean/tasks/clean' {
  declare module.exports: any;
}

// Filename aliases
declare module 'grunt-contrib-clean/tasks/clean.js' {
  declare module.exports: $Exports<'grunt-contrib-clean/tasks/clean'>;
}
