// flow-typed signature: 9f8986b0f5c27584d8f404efdfdcb7c0
// flow-typed version: <<STUB>>/grunt-contrib-connect_v2.1.0/flow_v0.123.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'grunt-contrib-connect'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'grunt-contrib-connect' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'grunt-contrib-connect/tasks/connect' {
  declare module.exports: any;
}

// Filename aliases
declare module 'grunt-contrib-connect/tasks/connect.js' {
  declare module.exports: $Exports<'grunt-contrib-connect/tasks/connect'>;
}
