// flow-typed signature: 2fe17f6ece7c35afd9fb32b6a7f33800
// flow-typed version: <<STUB>>/grunt-contrib-watch_v1.1.0/flow_v0.123.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'grunt-contrib-watch'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'grunt-contrib-watch' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'grunt-contrib-watch/tasks/lib/livereload' {
  declare module.exports: any;
}

declare module 'grunt-contrib-watch/tasks/lib/taskrun' {
  declare module.exports: any;
}

declare module 'grunt-contrib-watch/tasks/lib/taskrunner' {
  declare module.exports: any;
}

declare module 'grunt-contrib-watch/tasks/watch' {
  declare module.exports: any;
}

// Filename aliases
declare module 'grunt-contrib-watch/tasks/lib/livereload.js' {
  declare module.exports: $Exports<'grunt-contrib-watch/tasks/lib/livereload'>;
}
declare module 'grunt-contrib-watch/tasks/lib/taskrun.js' {
  declare module.exports: $Exports<'grunt-contrib-watch/tasks/lib/taskrun'>;
}
declare module 'grunt-contrib-watch/tasks/lib/taskrunner.js' {
  declare module.exports: $Exports<'grunt-contrib-watch/tasks/lib/taskrunner'>;
}
declare module 'grunt-contrib-watch/tasks/watch.js' {
  declare module.exports: $Exports<'grunt-contrib-watch/tasks/watch'>;
}
