// flow-typed signature: 70af788808e7a0e1c4a6a64c8b058e10
// flow-typed version: <<STUB>>/grunt-check-dependencies_v1.0.0/flow_v0.123.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'grunt-check-dependencies'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'grunt-check-dependencies' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'grunt-check-dependencies/tasks/check-dependencies' {
  declare module.exports: any;
}

// Filename aliases
declare module 'grunt-check-dependencies/tasks/check-dependencies.js' {
  declare module.exports: $Exports<'grunt-check-dependencies/tasks/check-dependencies'>;
}
