// flow-typed signature: 939b7dc05b21da2a1b525baa63a19087
// flow-typed version: <<STUB>>/grunt-exec_v3.0.0/flow_v0.123.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'grunt-exec'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'grunt-exec' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'grunt-exec/Gruntfile' {
  declare module.exports: any;
}

declare module 'grunt-exec/tasks/exec' {
  declare module.exports: any;
}

declare module 'grunt-exec/test/Gruntfile' {
  declare module.exports: any;
}

declare module 'grunt-exec/test/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'grunt-exec/Gruntfile.js' {
  declare module.exports: $Exports<'grunt-exec/Gruntfile'>;
}
declare module 'grunt-exec/tasks/exec.js' {
  declare module.exports: $Exports<'grunt-exec/tasks/exec'>;
}
declare module 'grunt-exec/test/Gruntfile.js' {
  declare module.exports: $Exports<'grunt-exec/test/Gruntfile'>;
}
declare module 'grunt-exec/test/test.js' {
  declare module.exports: $Exports<'grunt-exec/test/test'>;
}
