// flow-typed signature: 3676f7060bc8c0c73dab212b4faf5973
// flow-typed version: <<STUB>>/load-grunt-tasks_v5.1.0/flow_v0.123.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'load-grunt-tasks'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'load-grunt-tasks' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'load-grunt-tasks/index' {
  declare module.exports: $Exports<'load-grunt-tasks'>;
}
declare module 'load-grunt-tasks/index.js' {
  declare module.exports: $Exports<'load-grunt-tasks'>;
}
