// flow-typed signature: 0ed772ee53347544fa8f3c0226884963
// flow-typed version: <<STUB>>/multihashes_v0.4.15/flow_v0.123.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'multihashes'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'multihashes' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'multihashes/dist' {
  declare module.exports: any;
}

declare module 'multihashes/dist/index.min' {
  declare module.exports: any;
}

declare module 'multihashes/example' {
  declare module.exports: any;
}

declare module 'multihashes/src/constants' {
  declare module.exports: any;
}

declare module 'multihashes/src' {
  declare module.exports: any;
}

// Filename aliases
declare module 'multihashes/dist/index' {
  declare module.exports: $Exports<'multihashes/dist'>;
}
declare module 'multihashes/dist/index.js' {
  declare module.exports: $Exports<'multihashes/dist'>;
}
declare module 'multihashes/dist/index.min.js' {
  declare module.exports: $Exports<'multihashes/dist/index.min'>;
}
declare module 'multihashes/example.js' {
  declare module.exports: $Exports<'multihashes/example'>;
}
declare module 'multihashes/src/constants.js' {
  declare module.exports: $Exports<'multihashes/src/constants'>;
}
declare module 'multihashes/src/index' {
  declare module.exports: $Exports<'multihashes/src'>;
}
declare module 'multihashes/src/index.js' {
  declare module.exports: $Exports<'multihashes/src'>;
}
