// flow-typed signature: abc426704f97ad694a275c4e780257a0
// flow-typed version: <<STUB>>/nacl-stream_v0.3.5/flow_v0.123.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'nacl-stream'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'nacl-stream' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'nacl-stream/nacl-stream' {
  declare module.exports: any;
}

declare module 'nacl-stream/nacl-stream.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'nacl-stream/nacl-stream.js' {
  declare module.exports: $Exports<'nacl-stream/nacl-stream'>;
}
declare module 'nacl-stream/nacl-stream.min.js' {
  declare module.exports: $Exports<'nacl-stream/nacl-stream.min'>;
}
