// flow-typed signature: babae7b70ee7791f0c0787d2d5801fb4
// flow-typed version: <<STUB>>/nacl-blob_v2.0.2/flow_v0.123.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'nacl-blob'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'nacl-blob' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'nacl-blob/decrypt-worker' {
  declare module.exports: any;
}

declare module 'nacl-blob/dist' {
  declare module.exports: any;
}

declare module 'nacl-blob/encrypt-worker' {
  declare module.exports: any;
}

declare module 'nacl-blob/example' {
  declare module.exports: any;
}

declare module 'nacl-blob/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'nacl-blob/decrypt-worker.js' {
  declare module.exports: $Exports<'nacl-blob/decrypt-worker'>;
}
declare module 'nacl-blob/dist/index' {
  declare module.exports: $Exports<'nacl-blob/dist'>;
}
declare module 'nacl-blob/dist/index.js' {
  declare module.exports: $Exports<'nacl-blob/dist'>;
}
declare module 'nacl-blob/encrypt-worker.js' {
  declare module.exports: $Exports<'nacl-blob/encrypt-worker'>;
}
declare module 'nacl-blob/example.js' {
  declare module.exports: $Exports<'nacl-blob/example'>;
}
declare module 'nacl-blob/index' {
  declare module.exports: $Exports<'nacl-blob'>;
}
declare module 'nacl-blob/index.js' {
  declare module.exports: $Exports<'nacl-blob'>;
}
declare module 'nacl-blob/test.js' {
  declare module.exports: $Exports<'nacl-blob/test'>;
}
