// flow-typed signature: 65194475977c3965d2064f3b9ca9620c
// flow-typed version: <<STUB>>/primus_v7.3.4/flow_v0.123.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'primus'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'primus' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'primus/dist/primus' {
  declare module.exports: any;
}

declare module 'primus/errors' {
  declare module.exports: any;
}

declare module 'primus/middleware/access-control' {
  declare module.exports: any;
}

declare module 'primus/middleware/authorization' {
  declare module.exports: any;
}

declare module 'primus/middleware/error' {
  declare module.exports: any;
}

declare module 'primus/middleware/forwarded' {
  declare module.exports: any;
}

declare module 'primus/middleware/no-cache' {
  declare module.exports: any;
}

declare module 'primus/middleware/primus' {
  declare module.exports: any;
}

declare module 'primus/middleware/spec' {
  declare module.exports: any;
}

declare module 'primus/middleware/xss' {
  declare module.exports: any;
}

declare module 'primus/parsers/binary' {
  declare module.exports: any;
}

declare module 'primus/parsers/ejson' {
  declare module.exports: any;
}

declare module 'primus/parsers/json' {
  declare module.exports: any;
}

declare module 'primus/parsers/msgpack' {
  declare module.exports: any;
}

declare module 'primus/primus' {
  declare module.exports: any;
}

declare module 'primus/spark' {
  declare module.exports: any;
}

declare module 'primus/transformer' {
  declare module.exports: any;
}

declare module 'primus/transformers/browserchannel/client' {
  declare module.exports: any;
}

declare module 'primus/transformers/browserchannel' {
  declare module.exports: any;
}

declare module 'primus/transformers/browserchannel/server' {
  declare module.exports: any;
}

declare module 'primus/transformers/engine.io/client' {
  declare module.exports: any;
}

declare module 'primus/transformers/engine.io' {
  declare module.exports: any;
}

declare module 'primus/transformers/engine.io/library' {
  declare module.exports: any;
}

declare module 'primus/transformers/engine.io/server' {
  declare module.exports: any;
}

declare module 'primus/transformers/faye/client' {
  declare module.exports: any;
}

declare module 'primus/transformers/faye' {
  declare module.exports: any;
}

declare module 'primus/transformers/faye/server' {
  declare module.exports: any;
}

declare module 'primus/transformers/sockjs/client' {
  declare module.exports: any;
}

declare module 'primus/transformers/sockjs' {
  declare module.exports: any;
}

declare module 'primus/transformers/sockjs/library' {
  declare module.exports: any;
}

declare module 'primus/transformers/sockjs/server' {
  declare module.exports: any;
}

declare module 'primus/transformers/uws' {
  declare module.exports: any;
}

declare module 'primus/transformers/uws/server' {
  declare module.exports: any;
}

declare module 'primus/transformers/websockets/client' {
  declare module.exports: any;
}

declare module 'primus/transformers/websockets' {
  declare module.exports: any;
}

declare module 'primus/transformers/websockets/server' {
  declare module.exports: any;
}

// Filename aliases
declare module 'primus/dist/primus.js' {
  declare module.exports: $Exports<'primus/dist/primus'>;
}
declare module 'primus/errors.js' {
  declare module.exports: $Exports<'primus/errors'>;
}
declare module 'primus/index' {
  declare module.exports: $Exports<'primus'>;
}
declare module 'primus/index.js' {
  declare module.exports: $Exports<'primus'>;
}
declare module 'primus/middleware/access-control.js' {
  declare module.exports: $Exports<'primus/middleware/access-control'>;
}
declare module 'primus/middleware/authorization.js' {
  declare module.exports: $Exports<'primus/middleware/authorization'>;
}
declare module 'primus/middleware/error.js' {
  declare module.exports: $Exports<'primus/middleware/error'>;
}
declare module 'primus/middleware/forwarded.js' {
  declare module.exports: $Exports<'primus/middleware/forwarded'>;
}
declare module 'primus/middleware/no-cache.js' {
  declare module.exports: $Exports<'primus/middleware/no-cache'>;
}
declare module 'primus/middleware/primus.js' {
  declare module.exports: $Exports<'primus/middleware/primus'>;
}
declare module 'primus/middleware/spec.js' {
  declare module.exports: $Exports<'primus/middleware/spec'>;
}
declare module 'primus/middleware/xss.js' {
  declare module.exports: $Exports<'primus/middleware/xss'>;
}
declare module 'primus/parsers/binary.js' {
  declare module.exports: $Exports<'primus/parsers/binary'>;
}
declare module 'primus/parsers/ejson.js' {
  declare module.exports: $Exports<'primus/parsers/ejson'>;
}
declare module 'primus/parsers/json.js' {
  declare module.exports: $Exports<'primus/parsers/json'>;
}
declare module 'primus/parsers/msgpack.js' {
  declare module.exports: $Exports<'primus/parsers/msgpack'>;
}
declare module 'primus/primus.js' {
  declare module.exports: $Exports<'primus/primus'>;
}
declare module 'primus/spark.js' {
  declare module.exports: $Exports<'primus/spark'>;
}
declare module 'primus/transformer.js' {
  declare module.exports: $Exports<'primus/transformer'>;
}
declare module 'primus/transformers/browserchannel/client.js' {
  declare module.exports: $Exports<'primus/transformers/browserchannel/client'>;
}
declare module 'primus/transformers/browserchannel/index' {
  declare module.exports: $Exports<'primus/transformers/browserchannel'>;
}
declare module 'primus/transformers/browserchannel/index.js' {
  declare module.exports: $Exports<'primus/transformers/browserchannel'>;
}
declare module 'primus/transformers/browserchannel/server.js' {
  declare module.exports: $Exports<'primus/transformers/browserchannel/server'>;
}
declare module 'primus/transformers/engine.io/client.js' {
  declare module.exports: $Exports<'primus/transformers/engine.io/client'>;
}
declare module 'primus/transformers/engine.io/index' {
  declare module.exports: $Exports<'primus/transformers/engine.io'>;
}
declare module 'primus/transformers/engine.io/index.js' {
  declare module.exports: $Exports<'primus/transformers/engine.io'>;
}
declare module 'primus/transformers/engine.io/library.js' {
  declare module.exports: $Exports<'primus/transformers/engine.io/library'>;
}
declare module 'primus/transformers/engine.io/server.js' {
  declare module.exports: $Exports<'primus/transformers/engine.io/server'>;
}
declare module 'primus/transformers/faye/client.js' {
  declare module.exports: $Exports<'primus/transformers/faye/client'>;
}
declare module 'primus/transformers/faye/index' {
  declare module.exports: $Exports<'primus/transformers/faye'>;
}
declare module 'primus/transformers/faye/index.js' {
  declare module.exports: $Exports<'primus/transformers/faye'>;
}
declare module 'primus/transformers/faye/server.js' {
  declare module.exports: $Exports<'primus/transformers/faye/server'>;
}
declare module 'primus/transformers/sockjs/client.js' {
  declare module.exports: $Exports<'primus/transformers/sockjs/client'>;
}
declare module 'primus/transformers/sockjs/index' {
  declare module.exports: $Exports<'primus/transformers/sockjs'>;
}
declare module 'primus/transformers/sockjs/index.js' {
  declare module.exports: $Exports<'primus/transformers/sockjs'>;
}
declare module 'primus/transformers/sockjs/library.js' {
  declare module.exports: $Exports<'primus/transformers/sockjs/library'>;
}
declare module 'primus/transformers/sockjs/server.js' {
  declare module.exports: $Exports<'primus/transformers/sockjs/server'>;
}
declare module 'primus/transformers/uws/index' {
  declare module.exports: $Exports<'primus/transformers/uws'>;
}
declare module 'primus/transformers/uws/index.js' {
  declare module.exports: $Exports<'primus/transformers/uws'>;
}
declare module 'primus/transformers/uws/server.js' {
  declare module.exports: $Exports<'primus/transformers/uws/server'>;
}
declare module 'primus/transformers/websockets/client.js' {
  declare module.exports: $Exports<'primus/transformers/websockets/client'>;
}
declare module 'primus/transformers/websockets/index' {
  declare module.exports: $Exports<'primus/transformers/websockets'>;
}
declare module 'primus/transformers/websockets/index.js' {
  declare module.exports: $Exports<'primus/transformers/websockets'>;
}
declare module 'primus/transformers/websockets/server.js' {
  declare module.exports: $Exports<'primus/transformers/websockets/server'>;
}
