// flow-typed signature: e29403a51a8e56ab9779f7472183898e
// flow-typed version: <<STUB>>/primus-rooms_v3.4.1/flow_v0.123.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'primus-rooms'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'primus-rooms' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'primus-rooms/lib/error' {
  declare module.exports: any;
}

declare module 'primus-rooms/lib' {
  declare module.exports: any;
}

declare module 'primus-rooms/lib/rooms' {
  declare module.exports: any;
}

// Filename aliases
declare module 'primus-rooms/index' {
  declare module.exports: $Exports<'primus-rooms'>;
}
declare module 'primus-rooms/index.js' {
  declare module.exports: $Exports<'primus-rooms'>;
}
declare module 'primus-rooms/lib/error.js' {
  declare module.exports: $Exports<'primus-rooms/lib/error'>;
}
declare module 'primus-rooms/lib/index' {
  declare module.exports: $Exports<'primus-rooms/lib'>;
}
declare module 'primus-rooms/lib/index.js' {
  declare module.exports: $Exports<'primus-rooms/lib'>;
}
declare module 'primus-rooms/lib/rooms.js' {
  declare module.exports: $Exports<'primus-rooms/lib/rooms'>;
}
