// flow-typed signature: 71178a4eb1a5020b6f0c6617c55188db
// flow-typed version: <<STUB>>/pug-lint-vue_v0.4.0/flow_v0.123.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'pug-lint-vue'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'pug-lint-vue' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'pug-lint-vue/lib/cli' {
  declare module.exports: any;
}

declare module 'pug-lint-vue/lib/linter' {
  declare module.exports: any;
}

declare module 'pug-lint-vue/lib/reporter' {
  declare module.exports: any;
}

// Filename aliases
declare module 'pug-lint-vue/lib/cli.js' {
  declare module.exports: $Exports<'pug-lint-vue/lib/cli'>;
}
declare module 'pug-lint-vue/lib/linter.js' {
  declare module.exports: $Exports<'pug-lint-vue/lib/linter'>;
}
declare module 'pug-lint-vue/lib/reporter.js' {
  declare module.exports: $Exports<'pug-lint-vue/lib/reporter'>;
}
