// flow-typed signature: 9ef717d7640eddece9e519c685768d56
// flow-typed version: <<STUB>>/rollup-plugin-sass_v1.2.2/flow_v0.123.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'rollup-plugin-sass'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'rollup-plugin-sass' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'rollup-plugin-sass/dist' {
  declare module.exports: any;
}

declare module 'rollup-plugin-sass/dist/style' {
  declare module.exports: any;
}

// Filename aliases
declare module 'rollup-plugin-sass/dist/index' {
  declare module.exports: $Exports<'rollup-plugin-sass/dist'>;
}
declare module 'rollup-plugin-sass/dist/index.js' {
  declare module.exports: $Exports<'rollup-plugin-sass/dist'>;
}
declare module 'rollup-plugin-sass/dist/style.js' {
  declare module.exports: $Exports<'rollup-plugin-sass/dist/style'>;
}
