// flow-typed signature: bdbf14ecf2fa6670885d42334971ab6f
// flow-typed version: <<STUB>>/rollup-plugin-eslint_vokTurtles/rollup-plugin-eslint#22776453edd6d70cecf007c24f7727a9d9e2ca2a/flow_v0.123.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'rollup-plugin-eslint'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'rollup-plugin-eslint' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'rollup-plugin-eslint/index' {
  declare module.exports: $Exports<'rollup-plugin-eslint'>;
}
declare module 'rollup-plugin-eslint/index.js' {
  declare module.exports: $Exports<'rollup-plugin-eslint'>;
}
