// flow-typed signature: 97996298c50c5b22bd83e627283c8133
// flow-typed version: <<STUB>>/rollup-plugin-alias_v2.2.0/flow_v0.123.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'rollup-plugin-alias'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'rollup-plugin-alias' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'rollup-plugin-alias/dist/rollup-plugin-alias.es2015' {
  declare module.exports: any;
}

declare module 'rollup-plugin-alias/dist/rollup-plugin-alias' {
  declare module.exports: any;
}

declare module 'rollup-plugin-alias/src' {
  declare module.exports: any;
}

// Filename aliases
declare module 'rollup-plugin-alias/dist/rollup-plugin-alias.es2015.js' {
  declare module.exports: $Exports<'rollup-plugin-alias/dist/rollup-plugin-alias.es2015'>;
}
declare module 'rollup-plugin-alias/dist/rollup-plugin-alias.js' {
  declare module.exports: $Exports<'rollup-plugin-alias/dist/rollup-plugin-alias'>;
}
declare module 'rollup-plugin-alias/src/index' {
  declare module.exports: $Exports<'rollup-plugin-alias/src'>;
}
declare module 'rollup-plugin-alias/src/index.js' {
  declare module.exports: $Exports<'rollup-plugin-alias/src'>;
}
