// flow-typed signature: b9be15942b728626191cac95937d8567
// flow-typed version: <<STUB>>/scrypt-async_v2.0.1/flow_v0.123.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'scrypt-async'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'scrypt-async' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'scrypt-async/scrypt-async' {
  declare module.exports: any;
}

declare module 'scrypt-async/scrypt-async.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'scrypt-async/scrypt-async.js' {
  declare module.exports: $Exports<'scrypt-async/scrypt-async'>;
}
declare module 'scrypt-async/scrypt-async.min.js' {
  declare module.exports: $Exports<'scrypt-async/scrypt-async.min'>;
}
