// flow-typed signature: 0998c792d79e34b83ca333a22ededdc8
// flow-typed version: <<STUB>>/should-sinon_v0.0.6/flow_v0.123.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'should-sinon'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'should-sinon' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'should-sinon/should-sinon' {
  declare module.exports: any;
}

declare module 'should-sinon/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'should-sinon/should-sinon.js' {
  declare module.exports: $Exports<'should-sinon/should-sinon'>;
}
declare module 'should-sinon/test.js' {
  declare module.exports: $Exports<'should-sinon/test'>;
}
