// flow-typed signature: ff7c4b0f38b952b106ac864332ccef68
// flow-typed version: <<STUB>>/systemjs_v6.1.4/flow_v0.123.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'systemjs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'systemjs' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'systemjs/dist/extras/amd' {
  declare module.exports: any;
}

declare module 'systemjs/dist/extras/amd.min' {
  declare module.exports: any;
}

declare module 'systemjs/dist/extras/global' {
  declare module.exports: any;
}

declare module 'systemjs/dist/extras/global.min' {
  declare module.exports: any;
}

declare module 'systemjs/dist/extras/module-types' {
  declare module.exports: any;
}

declare module 'systemjs/dist/extras/module-types.min' {
  declare module.exports: any;
}

declare module 'systemjs/dist/extras/named-exports' {
  declare module.exports: any;
}

declare module 'systemjs/dist/extras/named-exports.min' {
  declare module.exports: any;
}

declare module 'systemjs/dist/extras/named-register' {
  declare module.exports: any;
}

declare module 'systemjs/dist/extras/named-register.min' {
  declare module.exports: any;
}

declare module 'systemjs/dist/extras/transform' {
  declare module.exports: any;
}

declare module 'systemjs/dist/extras/transform.min' {
  declare module.exports: any;
}

declare module 'systemjs/dist/extras/use-default' {
  declare module.exports: any;
}

declare module 'systemjs/dist/extras/use-default.min' {
  declare module.exports: any;
}

declare module 'systemjs/dist/s' {
  declare module.exports: any;
}

declare module 'systemjs/dist/s.min' {
  declare module.exports: any;
}

declare module 'systemjs/dist/system' {
  declare module.exports: any;
}

declare module 'systemjs/dist/system.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'systemjs/dist/extras/amd.js' {
  declare module.exports: $Exports<'systemjs/dist/extras/amd'>;
}
declare module 'systemjs/dist/extras/amd.min.js' {
  declare module.exports: $Exports<'systemjs/dist/extras/amd.min'>;
}
declare module 'systemjs/dist/extras/global.js' {
  declare module.exports: $Exports<'systemjs/dist/extras/global'>;
}
declare module 'systemjs/dist/extras/global.min.js' {
  declare module.exports: $Exports<'systemjs/dist/extras/global.min'>;
}
declare module 'systemjs/dist/extras/module-types.js' {
  declare module.exports: $Exports<'systemjs/dist/extras/module-types'>;
}
declare module 'systemjs/dist/extras/module-types.min.js' {
  declare module.exports: $Exports<'systemjs/dist/extras/module-types.min'>;
}
declare module 'systemjs/dist/extras/named-exports.js' {
  declare module.exports: $Exports<'systemjs/dist/extras/named-exports'>;
}
declare module 'systemjs/dist/extras/named-exports.min.js' {
  declare module.exports: $Exports<'systemjs/dist/extras/named-exports.min'>;
}
declare module 'systemjs/dist/extras/named-register.js' {
  declare module.exports: $Exports<'systemjs/dist/extras/named-register'>;
}
declare module 'systemjs/dist/extras/named-register.min.js' {
  declare module.exports: $Exports<'systemjs/dist/extras/named-register.min'>;
}
declare module 'systemjs/dist/extras/transform.js' {
  declare module.exports: $Exports<'systemjs/dist/extras/transform'>;
}
declare module 'systemjs/dist/extras/transform.min.js' {
  declare module.exports: $Exports<'systemjs/dist/extras/transform.min'>;
}
declare module 'systemjs/dist/extras/use-default.js' {
  declare module.exports: $Exports<'systemjs/dist/extras/use-default'>;
}
declare module 'systemjs/dist/extras/use-default.min.js' {
  declare module.exports: $Exports<'systemjs/dist/extras/use-default.min'>;
}
declare module 'systemjs/dist/s.js' {
  declare module.exports: $Exports<'systemjs/dist/s'>;
}
declare module 'systemjs/dist/s.min.js' {
  declare module.exports: $Exports<'systemjs/dist/s.min'>;
}
declare module 'systemjs/dist/system.js' {
  declare module.exports: $Exports<'systemjs/dist/system'>;
}
declare module 'systemjs/dist/system.min.js' {
  declare module.exports: $Exports<'systemjs/dist/system.min'>;
}
