// flow-typed signature: 9bad240a48bf811beeb9d5075eef7c0a
// flow-typed version: <<STUB>>/velocity-animate_v1.5.2/flow_v0.123.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'velocity-animate'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'velocity-animate' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'velocity-animate/velocity' {
  declare module.exports: any;
}

declare module 'velocity-animate/velocity.min' {
  declare module.exports: any;
}

declare module 'velocity-animate/velocity.ui' {
  declare module.exports: any;
}

declare module 'velocity-animate/velocity.ui.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'velocity-animate/velocity.js' {
  declare module.exports: $Exports<'velocity-animate/velocity'>;
}
declare module 'velocity-animate/velocity.min.js' {
  declare module.exports: $Exports<'velocity-animate/velocity.min'>;
}
declare module 'velocity-animate/velocity.ui.js' {
  declare module.exports: $Exports<'velocity-animate/velocity.ui'>;
}
declare module 'velocity-animate/velocity.ui.min.js' {
  declare module.exports: $Exports<'velocity-animate/velocity.ui.min'>;
}
