// flow-typed signature: 639e9587bc239cba2d498252cbd0ff03
// flow-typed version: <<STUB>>/vue-router_v3.1.6/flow_v0.123.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'vue-router'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'vue-router' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'vue-router/dist/vue-router.common' {
  declare module.exports: any;
}

declare module 'vue-router/dist/vue-router.esm.browser' {
  declare module.exports: any;
}

declare module 'vue-router/dist/vue-router.esm.browser.min' {
  declare module.exports: any;
}

declare module 'vue-router/dist/vue-router.esm' {
  declare module.exports: any;
}

declare module 'vue-router/dist/vue-router' {
  declare module.exports: any;
}

declare module 'vue-router/dist/vue-router.min' {
  declare module.exports: any;
}

declare module 'vue-router/src/components/link' {
  declare module.exports: any;
}

declare module 'vue-router/src/components/view' {
  declare module.exports: any;
}

declare module 'vue-router/src/create-matcher' {
  declare module.exports: any;
}

declare module 'vue-router/src/create-route-map' {
  declare module.exports: any;
}

declare module 'vue-router/src/history/abstract' {
  declare module.exports: any;
}

declare module 'vue-router/src/history/base' {
  declare module.exports: any;
}

declare module 'vue-router/src/history/errors' {
  declare module.exports: any;
}

declare module 'vue-router/src/history/hash' {
  declare module.exports: any;
}

declare module 'vue-router/src/history/html5' {
  declare module.exports: any;
}

declare module 'vue-router/src' {
  declare module.exports: any;
}

declare module 'vue-router/src/install' {
  declare module.exports: any;
}

declare module 'vue-router/src/util/async' {
  declare module.exports: any;
}

declare module 'vue-router/src/util/dom' {
  declare module.exports: any;
}

declare module 'vue-router/src/util/location' {
  declare module.exports: any;
}

declare module 'vue-router/src/util/misc' {
  declare module.exports: any;
}

declare module 'vue-router/src/util/params' {
  declare module.exports: any;
}

declare module 'vue-router/src/util/path' {
  declare module.exports: any;
}

declare module 'vue-router/src/util/push-state' {
  declare module.exports: any;
}

declare module 'vue-router/src/util/query' {
  declare module.exports: any;
}

declare module 'vue-router/src/util/resolve-components' {
  declare module.exports: any;
}

declare module 'vue-router/src/util/route' {
  declare module.exports: any;
}

declare module 'vue-router/src/util/scroll' {
  declare module.exports: any;
}

declare module 'vue-router/src/util/state-key' {
  declare module.exports: any;
}

declare module 'vue-router/src/util/warn' {
  declare module.exports: any;
}

// Filename aliases
declare module 'vue-router/dist/vue-router.common.js' {
  declare module.exports: $Exports<'vue-router/dist/vue-router.common'>;
}
declare module 'vue-router/dist/vue-router.esm.browser.js' {
  declare module.exports: $Exports<'vue-router/dist/vue-router.esm.browser'>;
}
declare module 'vue-router/dist/vue-router.esm.browser.min.js' {
  declare module.exports: $Exports<'vue-router/dist/vue-router.esm.browser.min'>;
}
declare module 'vue-router/dist/vue-router.esm.js' {
  declare module.exports: $Exports<'vue-router/dist/vue-router.esm'>;
}
declare module 'vue-router/dist/vue-router.js' {
  declare module.exports: $Exports<'vue-router/dist/vue-router'>;
}
declare module 'vue-router/dist/vue-router.min.js' {
  declare module.exports: $Exports<'vue-router/dist/vue-router.min'>;
}
declare module 'vue-router/src/components/link.js' {
  declare module.exports: $Exports<'vue-router/src/components/link'>;
}
declare module 'vue-router/src/components/view.js' {
  declare module.exports: $Exports<'vue-router/src/components/view'>;
}
declare module 'vue-router/src/create-matcher.js' {
  declare module.exports: $Exports<'vue-router/src/create-matcher'>;
}
declare module 'vue-router/src/create-route-map.js' {
  declare module.exports: $Exports<'vue-router/src/create-route-map'>;
}
declare module 'vue-router/src/history/abstract.js' {
  declare module.exports: $Exports<'vue-router/src/history/abstract'>;
}
declare module 'vue-router/src/history/base.js' {
  declare module.exports: $Exports<'vue-router/src/history/base'>;
}
declare module 'vue-router/src/history/errors.js' {
  declare module.exports: $Exports<'vue-router/src/history/errors'>;
}
declare module 'vue-router/src/history/hash.js' {
  declare module.exports: $Exports<'vue-router/src/history/hash'>;
}
declare module 'vue-router/src/history/html5.js' {
  declare module.exports: $Exports<'vue-router/src/history/html5'>;
}
declare module 'vue-router/src/index' {
  declare module.exports: $Exports<'vue-router/src'>;
}
declare module 'vue-router/src/index.js' {
  declare module.exports: $Exports<'vue-router/src'>;
}
declare module 'vue-router/src/install.js' {
  declare module.exports: $Exports<'vue-router/src/install'>;
}
declare module 'vue-router/src/util/async.js' {
  declare module.exports: $Exports<'vue-router/src/util/async'>;
}
declare module 'vue-router/src/util/dom.js' {
  declare module.exports: $Exports<'vue-router/src/util/dom'>;
}
declare module 'vue-router/src/util/location.js' {
  declare module.exports: $Exports<'vue-router/src/util/location'>;
}
declare module 'vue-router/src/util/misc.js' {
  declare module.exports: $Exports<'vue-router/src/util/misc'>;
}
declare module 'vue-router/src/util/params.js' {
  declare module.exports: $Exports<'vue-router/src/util/params'>;
}
declare module 'vue-router/src/util/path.js' {
  declare module.exports: $Exports<'vue-router/src/util/path'>;
}
declare module 'vue-router/src/util/push-state.js' {
  declare module.exports: $Exports<'vue-router/src/util/push-state'>;
}
declare module 'vue-router/src/util/query.js' {
  declare module.exports: $Exports<'vue-router/src/util/query'>;
}
declare module 'vue-router/src/util/resolve-components.js' {
  declare module.exports: $Exports<'vue-router/src/util/resolve-components'>;
}
declare module 'vue-router/src/util/route.js' {
  declare module.exports: $Exports<'vue-router/src/util/route'>;
}
declare module 'vue-router/src/util/scroll.js' {
  declare module.exports: $Exports<'vue-router/src/util/scroll'>;
}
declare module 'vue-router/src/util/state-key.js' {
  declare module.exports: $Exports<'vue-router/src/util/state-key'>;
}
declare module 'vue-router/src/util/warn.js' {
  declare module.exports: $Exports<'vue-router/src/util/warn'>;
}
