// flow-typed signature: 975661d29cc0fae832b0378c9c4797af
// flow-typed version: <<STUB>>/vue-script2_v2.1.0/flow_v0.123.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'vue-script2'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'vue-script2' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'vue-script2/dist/vue-script2' {
  declare module.exports: any;
}

declare module 'vue-script2/dist/vue-script2.min' {
  declare module.exports: any;
}

declare module 'vue-script2/Gruntfile' {
  declare module.exports: any;
}

declare module 'vue-script2/src' {
  declare module.exports: any;
}

// Filename aliases
declare module 'vue-script2/dist/vue-script2.js' {
  declare module.exports: $Exports<'vue-script2/dist/vue-script2'>;
}
declare module 'vue-script2/dist/vue-script2.min.js' {
  declare module.exports: $Exports<'vue-script2/dist/vue-script2.min'>;
}
declare module 'vue-script2/Gruntfile.js' {
  declare module.exports: $Exports<'vue-script2/Gruntfile'>;
}
declare module 'vue-script2/src/index' {
  declare module.exports: $Exports<'vue-script2/src'>;
}
declare module 'vue-script2/src/index.js' {
  declare module.exports: $Exports<'vue-script2/src'>;
}
