// flow-typed signature: ad1233cb53c148eb88b84f5feb97a0e1
// flow-typed version: <<STUB>>/vue-cli-plugin-pug_v1.0.7/flow_v0.123.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'vue-cli-plugin-pug'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'vue-cli-plugin-pug' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'vue-cli-plugin-pug/index' {
  declare module.exports: $Exports<'vue-cli-plugin-pug'>;
}
declare module 'vue-cli-plugin-pug/index.js' {
  declare module.exports: $Exports<'vue-cli-plugin-pug'>;
}
