// flow-typed signature: 34ef14be80f7ed98ddfca65640a139d0
// flow-typed version: <<STUB>>/vue-clickaway_v2.2.2/flow_v0.123.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'vue-clickaway'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'vue-clickaway' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'vue-clickaway/build' {
  declare module.exports: any;
}

declare module 'vue-clickaway/dist/vue-clickaway.common' {
  declare module.exports: any;
}

declare module 'vue-clickaway/dist/vue-clickaway' {
  declare module.exports: any;
}

declare module 'vue-clickaway/dist/vue-clickaway.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'vue-clickaway/build.js' {
  declare module.exports: $Exports<'vue-clickaway/build'>;
}
declare module 'vue-clickaway/dist/vue-clickaway.common.js' {
  declare module.exports: $Exports<'vue-clickaway/dist/vue-clickaway.common'>;
}
declare module 'vue-clickaway/dist/vue-clickaway.js' {
  declare module.exports: $Exports<'vue-clickaway/dist/vue-clickaway'>;
}
declare module 'vue-clickaway/dist/vue-clickaway.min.js' {
  declare module.exports: $Exports<'vue-clickaway/dist/vue-clickaway.min'>;
}
declare module 'vue-clickaway/index' {
  declare module.exports: $Exports<'vue-clickaway'>;
}
declare module 'vue-clickaway/index.js' {
  declare module.exports: $Exports<'vue-clickaway'>;
}
