// flow-typed signature: fc5eaa2cbce40c15ffbb3214d1b69665
// flow-typed version: <<STUB>>/vue-slider-component_v3.0.41/flow_v0.123.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'vue-slider-component'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'vue-slider-component' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'vue-slider-component/dist-css/vue-slider-component.common' {
  declare module.exports: any;
}

declare module 'vue-slider-component/dist-css/vue-slider-component.umd' {
  declare module.exports: any;
}

declare module 'vue-slider-component/dist-css/vue-slider-component.umd.min' {
  declare module.exports: any;
}

declare module 'vue-slider-component/dist/vue-slider-component.common' {
  declare module.exports: any;
}

declare module 'vue-slider-component/dist/vue-slider-component.umd' {
  declare module.exports: any;
}

declare module 'vue-slider-component/dist/vue-slider-component.umd.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'vue-slider-component/dist-css/vue-slider-component.common.js' {
  declare module.exports: $Exports<'vue-slider-component/dist-css/vue-slider-component.common'>;
}
declare module 'vue-slider-component/dist-css/vue-slider-component.umd.js' {
  declare module.exports: $Exports<'vue-slider-component/dist-css/vue-slider-component.umd'>;
}
declare module 'vue-slider-component/dist-css/vue-slider-component.umd.min.js' {
  declare module.exports: $Exports<'vue-slider-component/dist-css/vue-slider-component.umd.min'>;
}
declare module 'vue-slider-component/dist/vue-slider-component.common.js' {
  declare module.exports: $Exports<'vue-slider-component/dist/vue-slider-component.common'>;
}
declare module 'vue-slider-component/dist/vue-slider-component.umd.js' {
  declare module.exports: $Exports<'vue-slider-component/dist/vue-slider-component.umd'>;
}
declare module 'vue-slider-component/dist/vue-slider-component.umd.min.js' {
  declare module.exports: $Exports<'vue-slider-component/dist/vue-slider-component.umd.min'>;
}
