// flow-typed signature: 3cfb840f4fca2624c80ca3f86f78aabb
// flow-typed version: <<STUB>>/wicg-inert_v3.0.2/flow_v0.123.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'wicg-inert'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'wicg-inert' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'wicg-inert/dist/inert' {
  declare module.exports: any;
}

declare module 'wicg-inert/dist/inert.min' {
  declare module.exports: any;
}

declare module 'wicg-inert/karma.conf' {
  declare module.exports: any;
}

declare module 'wicg-inert/rollup.config' {
  declare module.exports: any;
}

declare module 'wicg-inert/src/inert' {
  declare module.exports: any;
}

declare module 'wicg-inert/test/specs/basic.spec' {
  declare module.exports: any;
}

declare module 'wicg-inert/test/specs/element.spec' {
  declare module.exports: any;
}

declare module 'wicg-inert/test/specs/helpers' {
  declare module.exports: any;
}

declare module 'wicg-inert/test/specs/interactives.spec' {
  declare module.exports: any;
}

declare module 'wicg-inert/test/specs/nested.spec' {
  declare module.exports: any;
}

declare module 'wicg-inert/test/specs/reapply-aria-hidden.spec' {
  declare module.exports: any;
}

declare module 'wicg-inert/test/specs/reapply-tabindex.spec' {
  declare module.exports: any;
}

declare module 'wicg-inert/test/specs/shadow-dom-v0.spec' {
  declare module.exports: any;
}

declare module 'wicg-inert/test/specs/shadow-dom-v1.spec' {
  declare module.exports: any;
}

// Filename aliases
declare module 'wicg-inert/dist/inert.js' {
  declare module.exports: $Exports<'wicg-inert/dist/inert'>;
}
declare module 'wicg-inert/dist/inert.min.js' {
  declare module.exports: $Exports<'wicg-inert/dist/inert.min'>;
}
declare module 'wicg-inert/karma.conf.js' {
  declare module.exports: $Exports<'wicg-inert/karma.conf'>;
}
declare module 'wicg-inert/rollup.config.js' {
  declare module.exports: $Exports<'wicg-inert/rollup.config'>;
}
declare module 'wicg-inert/src/inert.js' {
  declare module.exports: $Exports<'wicg-inert/src/inert'>;
}
declare module 'wicg-inert/test/specs/basic.spec.js' {
  declare module.exports: $Exports<'wicg-inert/test/specs/basic.spec'>;
}
declare module 'wicg-inert/test/specs/element.spec.js' {
  declare module.exports: $Exports<'wicg-inert/test/specs/element.spec'>;
}
declare module 'wicg-inert/test/specs/helpers/index' {
  declare module.exports: $Exports<'wicg-inert/test/specs/helpers'>;
}
declare module 'wicg-inert/test/specs/helpers/index.js' {
  declare module.exports: $Exports<'wicg-inert/test/specs/helpers'>;
}
declare module 'wicg-inert/test/specs/interactives.spec.js' {
  declare module.exports: $Exports<'wicg-inert/test/specs/interactives.spec'>;
}
declare module 'wicg-inert/test/specs/nested.spec.js' {
  declare module.exports: $Exports<'wicg-inert/test/specs/nested.spec'>;
}
declare module 'wicg-inert/test/specs/reapply-aria-hidden.spec.js' {
  declare module.exports: $Exports<'wicg-inert/test/specs/reapply-aria-hidden.spec'>;
}
declare module 'wicg-inert/test/specs/reapply-tabindex.spec.js' {
  declare module.exports: $Exports<'wicg-inert/test/specs/reapply-tabindex.spec'>;
}
declare module 'wicg-inert/test/specs/shadow-dom-v0.spec.js' {
  declare module.exports: $Exports<'wicg-inert/test/specs/shadow-dom-v0.spec'>;
}
declare module 'wicg-inert/test/specs/shadow-dom-v1.spec.js' {
  declare module.exports: $Exports<'wicg-inert/test/specs/shadow-dom-v1.spec'>;
}
