// flow-typed signature: a412420b4dfdad7dbbe8870b62998b5c
// flow-typed version: <<STUB>>/@hapi/hapi_v19.1.1/flow_v0.123.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@hapi/hapi'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@hapi/hapi' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@hapi/hapi/lib/auth' {
  declare module.exports: any;
}

declare module '@hapi/hapi/lib/compression' {
  declare module.exports: any;
}

declare module '@hapi/hapi/lib/config' {
  declare module.exports: any;
}

declare module '@hapi/hapi/lib/core' {
  declare module.exports: any;
}

declare module '@hapi/hapi/lib/cors' {
  declare module.exports: any;
}

declare module '@hapi/hapi/lib/ext' {
  declare module.exports: any;
}

declare module '@hapi/hapi/lib/handler' {
  declare module.exports: any;
}

declare module '@hapi/hapi/lib/headers' {
  declare module.exports: any;
}

declare module '@hapi/hapi/lib' {
  declare module.exports: any;
}

declare module '@hapi/hapi/lib/methods' {
  declare module.exports: any;
}

declare module '@hapi/hapi/lib/request' {
  declare module.exports: any;
}

declare module '@hapi/hapi/lib/response' {
  declare module.exports: any;
}

declare module '@hapi/hapi/lib/route' {
  declare module.exports: any;
}

declare module '@hapi/hapi/lib/security' {
  declare module.exports: any;
}

declare module '@hapi/hapi/lib/server' {
  declare module.exports: any;
}

declare module '@hapi/hapi/lib/streams' {
  declare module.exports: any;
}

declare module '@hapi/hapi/lib/toolkit' {
  declare module.exports: any;
}

declare module '@hapi/hapi/lib/transmit' {
  declare module.exports: any;
}

declare module '@hapi/hapi/lib/validation' {
  declare module.exports: any;
}

// Filename aliases
declare module '@hapi/hapi/lib/auth.js' {
  declare module.exports: $Exports<'@hapi/hapi/lib/auth'>;
}
declare module '@hapi/hapi/lib/compression.js' {
  declare module.exports: $Exports<'@hapi/hapi/lib/compression'>;
}
declare module '@hapi/hapi/lib/config.js' {
  declare module.exports: $Exports<'@hapi/hapi/lib/config'>;
}
declare module '@hapi/hapi/lib/core.js' {
  declare module.exports: $Exports<'@hapi/hapi/lib/core'>;
}
declare module '@hapi/hapi/lib/cors.js' {
  declare module.exports: $Exports<'@hapi/hapi/lib/cors'>;
}
declare module '@hapi/hapi/lib/ext.js' {
  declare module.exports: $Exports<'@hapi/hapi/lib/ext'>;
}
declare module '@hapi/hapi/lib/handler.js' {
  declare module.exports: $Exports<'@hapi/hapi/lib/handler'>;
}
declare module '@hapi/hapi/lib/headers.js' {
  declare module.exports: $Exports<'@hapi/hapi/lib/headers'>;
}
declare module '@hapi/hapi/lib/index' {
  declare module.exports: $Exports<'@hapi/hapi/lib'>;
}
declare module '@hapi/hapi/lib/index.js' {
  declare module.exports: $Exports<'@hapi/hapi/lib'>;
}
declare module '@hapi/hapi/lib/methods.js' {
  declare module.exports: $Exports<'@hapi/hapi/lib/methods'>;
}
declare module '@hapi/hapi/lib/request.js' {
  declare module.exports: $Exports<'@hapi/hapi/lib/request'>;
}
declare module '@hapi/hapi/lib/response.js' {
  declare module.exports: $Exports<'@hapi/hapi/lib/response'>;
}
declare module '@hapi/hapi/lib/route.js' {
  declare module.exports: $Exports<'@hapi/hapi/lib/route'>;
}
declare module '@hapi/hapi/lib/security.js' {
  declare module.exports: $Exports<'@hapi/hapi/lib/security'>;
}
declare module '@hapi/hapi/lib/server.js' {
  declare module.exports: $Exports<'@hapi/hapi/lib/server'>;
}
declare module '@hapi/hapi/lib/streams.js' {
  declare module.exports: $Exports<'@hapi/hapi/lib/streams'>;
}
declare module '@hapi/hapi/lib/toolkit.js' {
  declare module.exports: $Exports<'@hapi/hapi/lib/toolkit'>;
}
declare module '@hapi/hapi/lib/transmit.js' {
  declare module.exports: $Exports<'@hapi/hapi/lib/transmit'>;
}
declare module '@hapi/hapi/lib/validation.js' {
  declare module.exports: $Exports<'@hapi/hapi/lib/validation'>;
}
