// flow-typed signature: 94fb6842f775143d5dc9076b1603f70c
// flow-typed version: <<STUB>>/@hapi/joi_v17.1.1/flow_v0.123.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@hapi/joi'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@hapi/joi' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@hapi/joi/dist/joi-browser.min' {
  declare module.exports: any;
}

declare module '@hapi/joi/lib/annotate' {
  declare module.exports: any;
}

declare module '@hapi/joi/lib/base' {
  declare module.exports: any;
}

declare module '@hapi/joi/lib/cache' {
  declare module.exports: any;
}

declare module '@hapi/joi/lib/common' {
  declare module.exports: any;
}

declare module '@hapi/joi/lib/compile' {
  declare module.exports: any;
}

declare module '@hapi/joi/lib/errors' {
  declare module.exports: any;
}

declare module '@hapi/joi/lib/extend' {
  declare module.exports: any;
}

declare module '@hapi/joi/lib' {
  declare module.exports: any;
}

declare module '@hapi/joi/lib/manifest' {
  declare module.exports: any;
}

declare module '@hapi/joi/lib/messages' {
  declare module.exports: any;
}

declare module '@hapi/joi/lib/modify' {
  declare module.exports: any;
}

declare module '@hapi/joi/lib/ref' {
  declare module.exports: any;
}

declare module '@hapi/joi/lib/schemas' {
  declare module.exports: any;
}

declare module '@hapi/joi/lib/state' {
  declare module.exports: any;
}

declare module '@hapi/joi/lib/template' {
  declare module.exports: any;
}

declare module '@hapi/joi/lib/trace' {
  declare module.exports: any;
}

declare module '@hapi/joi/lib/types/alternatives' {
  declare module.exports: any;
}

declare module '@hapi/joi/lib/types/any' {
  declare module.exports: any;
}

declare module '@hapi/joi/lib/types/array' {
  declare module.exports: any;
}

declare module '@hapi/joi/lib/types/binary' {
  declare module.exports: any;
}

declare module '@hapi/joi/lib/types/boolean' {
  declare module.exports: any;
}

declare module '@hapi/joi/lib/types/date' {
  declare module.exports: any;
}

declare module '@hapi/joi/lib/types/function' {
  declare module.exports: any;
}

declare module '@hapi/joi/lib/types/keys' {
  declare module.exports: any;
}

declare module '@hapi/joi/lib/types/link' {
  declare module.exports: any;
}

declare module '@hapi/joi/lib/types/number' {
  declare module.exports: any;
}

declare module '@hapi/joi/lib/types/object' {
  declare module.exports: any;
}

declare module '@hapi/joi/lib/types/string' {
  declare module.exports: any;
}

declare module '@hapi/joi/lib/types/symbol' {
  declare module.exports: any;
}

declare module '@hapi/joi/lib/validator' {
  declare module.exports: any;
}

declare module '@hapi/joi/lib/values' {
  declare module.exports: any;
}

// Filename aliases
declare module '@hapi/joi/dist/joi-browser.min.js' {
  declare module.exports: $Exports<'@hapi/joi/dist/joi-browser.min'>;
}
declare module '@hapi/joi/lib/annotate.js' {
  declare module.exports: $Exports<'@hapi/joi/lib/annotate'>;
}
declare module '@hapi/joi/lib/base.js' {
  declare module.exports: $Exports<'@hapi/joi/lib/base'>;
}
declare module '@hapi/joi/lib/cache.js' {
  declare module.exports: $Exports<'@hapi/joi/lib/cache'>;
}
declare module '@hapi/joi/lib/common.js' {
  declare module.exports: $Exports<'@hapi/joi/lib/common'>;
}
declare module '@hapi/joi/lib/compile.js' {
  declare module.exports: $Exports<'@hapi/joi/lib/compile'>;
}
declare module '@hapi/joi/lib/errors.js' {
  declare module.exports: $Exports<'@hapi/joi/lib/errors'>;
}
declare module '@hapi/joi/lib/extend.js' {
  declare module.exports: $Exports<'@hapi/joi/lib/extend'>;
}
declare module '@hapi/joi/lib/index' {
  declare module.exports: $Exports<'@hapi/joi/lib'>;
}
declare module '@hapi/joi/lib/index.js' {
  declare module.exports: $Exports<'@hapi/joi/lib'>;
}
declare module '@hapi/joi/lib/manifest.js' {
  declare module.exports: $Exports<'@hapi/joi/lib/manifest'>;
}
declare module '@hapi/joi/lib/messages.js' {
  declare module.exports: $Exports<'@hapi/joi/lib/messages'>;
}
declare module '@hapi/joi/lib/modify.js' {
  declare module.exports: $Exports<'@hapi/joi/lib/modify'>;
}
declare module '@hapi/joi/lib/ref.js' {
  declare module.exports: $Exports<'@hapi/joi/lib/ref'>;
}
declare module '@hapi/joi/lib/schemas.js' {
  declare module.exports: $Exports<'@hapi/joi/lib/schemas'>;
}
declare module '@hapi/joi/lib/state.js' {
  declare module.exports: $Exports<'@hapi/joi/lib/state'>;
}
declare module '@hapi/joi/lib/template.js' {
  declare module.exports: $Exports<'@hapi/joi/lib/template'>;
}
declare module '@hapi/joi/lib/trace.js' {
  declare module.exports: $Exports<'@hapi/joi/lib/trace'>;
}
declare module '@hapi/joi/lib/types/alternatives.js' {
  declare module.exports: $Exports<'@hapi/joi/lib/types/alternatives'>;
}
declare module '@hapi/joi/lib/types/any.js' {
  declare module.exports: $Exports<'@hapi/joi/lib/types/any'>;
}
declare module '@hapi/joi/lib/types/array.js' {
  declare module.exports: $Exports<'@hapi/joi/lib/types/array'>;
}
declare module '@hapi/joi/lib/types/binary.js' {
  declare module.exports: $Exports<'@hapi/joi/lib/types/binary'>;
}
declare module '@hapi/joi/lib/types/boolean.js' {
  declare module.exports: $Exports<'@hapi/joi/lib/types/boolean'>;
}
declare module '@hapi/joi/lib/types/date.js' {
  declare module.exports: $Exports<'@hapi/joi/lib/types/date'>;
}
declare module '@hapi/joi/lib/types/function.js' {
  declare module.exports: $Exports<'@hapi/joi/lib/types/function'>;
}
declare module '@hapi/joi/lib/types/keys.js' {
  declare module.exports: $Exports<'@hapi/joi/lib/types/keys'>;
}
declare module '@hapi/joi/lib/types/link.js' {
  declare module.exports: $Exports<'@hapi/joi/lib/types/link'>;
}
declare module '@hapi/joi/lib/types/number.js' {
  declare module.exports: $Exports<'@hapi/joi/lib/types/number'>;
}
declare module '@hapi/joi/lib/types/object.js' {
  declare module.exports: $Exports<'@hapi/joi/lib/types/object'>;
}
declare module '@hapi/joi/lib/types/string.js' {
  declare module.exports: $Exports<'@hapi/joi/lib/types/string'>;
}
declare module '@hapi/joi/lib/types/symbol.js' {
  declare module.exports: $Exports<'@hapi/joi/lib/types/symbol'>;
}
declare module '@hapi/joi/lib/validator.js' {
  declare module.exports: $Exports<'@hapi/joi/lib/validator'>;
}
declare module '@hapi/joi/lib/values.js' {
  declare module.exports: $Exports<'@hapi/joi/lib/values'>;
}
