name: NodeJS with Grunt

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04, ubuntu-24.04-arm]
        containers: [1, 2] # Uses 2 parallel instances
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 22
        cache: 'npm'
    - run: npm ci
    - name: Run Cypress
      run: npm test
      env:
        CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
        RUN_ID: ${{ github.sha }}-${{ github.run_id }}-${{ github.run_attempt }} # unique ID for every single workflow execution
        AGENT_OS: ${{ matrix.os }}
