name: NodeJS with Grunt

env:
  CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
  RUN_ID: ${{ github.sha }}-${{ github.run_id }}-${{ github.run_attempt }} # unique ID for every single workflow execution

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        # When secrets.CYPRESS_RECORD_KEY is not accessible(e.g. in forked PRs),
        # which is a condition where parallelization isn't enabled, fall back to a single container to avoid running tests twice.
        containers: ${{ secrets.CYPRESS_RECORD_KEY != '' && fromJSON('[1, 2]') || fromJSON('[1]') }}
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 22
        cache: 'npm'
    - run: npm ci
    - run: npm test
